using UnityEngine;
using UnityEngine.InputSystem;

public class Ca単onMovement : MonoBehaviour
{
    public Transform ca単on;
    public float rotationSpeed = 100f;

    private float currentAngleZ = 0f;
    private Vector2 input;
    private Quaternion initialRotation;

    private void Awake()
    {
        initialRotation = ca単on.localRotation;
    }

    public void OnLook(InputAction.CallbackContext context)
    {
        input = context.ReadValue<Vector2>();
    }

    private void Update()
    {
        float verticalInput = -input.y;

        currentAngleZ += verticalInput * rotationSpeed * Time.deltaTime;

        ca単on.localRotation = initialRotation * Quaternion.Euler(0, 0, currentAngleZ);
    }
}